modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/TheBlackSquidward/ResoruceChickens/issues"
license = "https://github.com/TheBlackSquidward/ResoruceChickens/blob/master/LICENSE"
[[mods]]
modId = "resourcechickens"
version = "1.0.0"
displayName = "Resource Chickens"
displayURL = "https://github.com/TheBlackSquidward/ResoruceChickens"
authors = "TheBlackSquidward"
description = '''Resource Chickens is a minecraft mod that provides an alternative way to generate resources through chickens.'''

[[dependencies.resourcechickens]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.resourcechickens]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"